name = "LswynPoint"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]] =
pattern = "laswayne.us.kg"
custom_domain = true
[[routes]] =
pattern = "support.zoom.us.laswayne.us.kg"
custom_domain = true

[vars]
PROXYIP = "83.142.30.5:2096"
UUID = "c68d755c-5220-4635-803f-52bb7c73b944"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
