name = "laswayne"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "35.185.180.129"
UUID = "c2987ac0-6b06-4ed6-a485-6ff487c29891"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
